# Generated by Django 5.2.15 on 2026-07-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('hex_code', models.CharField(blank=True, max_length=7, verbose_name='HEX-код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Обработка',
                'verbose_name_plural': 'Обработки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SteelGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steel_grades', to='references.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Марка стали',
                'verbose_name_plural': 'Марки стали',
                'ordering': ['material', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinishColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finish_colors', to='references.color', verbose_name='Цвет')),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finish_colors', to='references.finish', verbose_name='Обработка')),
            ],
            options={
                'verbose_name': 'Цвет обработки',
                'verbose_name_plural': 'Цвета обработок',
                'unique_together': {('finish', 'color')},
            },
        ),
    ]
