# Generated by Django 5.2.15 on 2026-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_group',
            field=models.CharField(blank=True, choices=[('white', 'Белые'), ('gray', 'Серые'), ('black', 'Чёрные'), ('brown', 'Коричневые'), ('blue', 'Синие'), ('green', 'Зелёные'), ('metallic', 'Металлик'), ('other', 'Другие')], max_length=20, verbose_name='Группа цвета'),
        ),
        migrations.AddField(
            model_name='color',
            name='ral_code',
            field=models.CharField(blank=True, help_text='Например: RAL 9010', max_length=20, verbose_name='RAL-код'),
        ),
        migrations.AddField(
            model_name='finish',
            name='color_ui',
            field=models.CharField(choices=[('swatches', 'Свотчи (≤10 цветов)'), ('ral_palette', 'Каталог RAL с поиском'), ('custom_request', '5 популярных + свой цвет')], default='swatches', help_text='Шлифованный/Полированный → «Каталог RAL». Под покраску → «5 популярных + свой цвет».', max_length=20, verbose_name='Интерфейс выбора цвета'),
        ),
    ]
