# Generated by Django 5.2.16 on 2026-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_color_color_group_color_ral_code_finish_color_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, help_text='Для карточки основного раздела на странице «Продукция»', upload_to='materials/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='material',
            name='landing_title',
            field=models.CharField(blank=True, help_text='Например «Изделия из нержавеющей стали». Пусто — материал не показывается основным разделом.', max_length=200, verbose_name='Заголовок на странице «Продукция»'),
        ),
    ]
