# Generated by Django 5.2.16 on 2026-07-11 10:33

import apps.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_material_image_material_landing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, help_text='Для карточки основного раздела на странице «Продукция». JPG, PNG или WebP, до 10 МБ, минимум 1000px по большей стороне. Фон лучше однотонный (белый/светлый) — на сайте фото вписывается целиком, без обрезки.', upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.validators.validate_image_filesize, apps.validators.validate_image_dimensions], verbose_name='Изображение'),
        ),
    ]
