# Generated by Django 5.2.16 on 2026-07-15 12:49

import django.db.models.deletion
from django.db import migrations, models


def copy_finish_colors_to_materials(apps, schema_editor):
    """Best-effort перенос палитр: цвета обработки достаются материалу,
    если в вариантах товаров эта обработка реально встречалась с этим
    материалом. Результат стоит проверить в админке («Материалы»)."""
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    FinishColor = apps.get_model('references', 'FinishColor')
    MaterialColor = apps.get_model('references', 'MaterialColor')

    pairs = set(
        ProductVariant.objects
        .filter(finish__isnull=False)
        .values_list('material_id', 'finish_id')
    )
    finish_colors = {}
    for fc in FinishColor.objects.all():
        finish_colors.setdefault(fc.finish_id, set()).add(fc.color_id)

    seen = set()
    rows = []
    for material_id, finish_id in pairs:
        for color_id in finish_colors.get(finish_id, ()):
            if (material_id, color_id) not in seen:
                seen.add((material_id, color_id))
                rows.append(MaterialColor(material_id=material_id, color_id=color_id))
    MaterialColor.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_alter_material_image'),
        ('catalog', '0008_product_image_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_colors', to='references.color', verbose_name='Цвет')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_colors', to='references.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Цвет материала',
                'verbose_name_plural': 'Цвета материалов',
                'unique_together': {('material', 'color')},
            },
        ),
        migrations.RunPython(copy_finish_colors_to_materials, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='FinishColor',
        ),
    ]
