# Generated by Django 5.2.16 on 2026-07-15 12:55

import django.db.models.deletion
from django.db import migrations, models


def copy_material_colors_to_grades(apps, schema_editor):
    """Best-effort перенос палитр: палитра материала копируется каждой его
    марке стали. Результат стоит проверить в админке («Марки стали»)."""
    SteelGrade = apps.get_model('references', 'SteelGrade')
    MaterialColor = apps.get_model('references', 'MaterialColor')
    SteelGradeColor = apps.get_model('references', 'SteelGradeColor')

    material_colors = {}
    for mc in MaterialColor.objects.all():
        material_colors.setdefault(mc.material_id, set()).add(mc.color_id)

    rows = []
    for grade in SteelGrade.objects.all():
        for color_id in material_colors.get(grade.material_id, ()):
            rows.append(SteelGradeColor(steel_grade_id=grade.pk, color_id=color_id))
    SteelGradeColor.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_materialcolor_delete_finishcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteelGradeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_colors', to='references.color', verbose_name='Цвет')),
                ('steel_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_colors', to='references.steelgrade', verbose_name='Марка стали')),
            ],
            options={
                'verbose_name': 'Цвет марки стали',
                'verbose_name_plural': 'Цвета марок стали',
                'unique_together': {('steel_grade', 'color')},
            },
        ),
        migrations.RunPython(copy_material_colors_to_grades, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='MaterialColor',
        ),
    ]
