# Generated by Django 5.2.16 on 2026-07-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_steelgradecolor_delete_materialcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_colors', to='references.color', verbose_name='Цвет')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_colors', to='references.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Цвет материала',
                'verbose_name_plural': 'Цвета материалов',
                'unique_together': {('material', 'color')},
            },
        ),
    ]
