# Generated by Django 5.2.16 on 2026-07-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_materialcolor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steelgradecolor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='steelgradecolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='steelgradecolor',
            name='steel_grade',
        ),
        migrations.DeleteModel(
            name='MaterialColor',
        ),
        migrations.DeleteModel(
            name='SteelGradeColor',
        ),
    ]
