# Generated by Django 5.2.16 on 2026-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_alter_steelgradecolor_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('colors', models.ManyToManyField(help_text='Оттенки, которые перенесутся на обработку при применении', related_name='palettes', to='references.color', verbose_name='Цвета')),
            ],
            options={
                'verbose_name': 'Палитра цветов',
                'verbose_name_plural': 'Палитры цветов',
                'ordering': ['name'],
            },
        ),
    ]
