# Generated by Django 5.2.16 on 2026-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_colorpalette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='colors',
            field=models.ManyToManyField(help_text='Набор оттенков. Меняется здесь — сразу отражается на всех обработках товаров, где выбрана эта палитра.', related_name='palettes', to='references.color', verbose_name='Цвета'),
        ),
    ]
