# Generated by Django 5.2.15 on 2026-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cart_snapshot', models.JSONField(blank=True, default=list, help_text='Слепок корзины на момент отправки: [{name, sku, qty, price, unit}]', verbose_name='Состав корзины')),
                ('source', models.CharField(choices=[('cart', 'Из корзины'), ('callback_request', 'Заявка на звонок')], default='cart', max_length=20, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('consent_pdn', models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
