# Generated by Django 5.2.16 on 2026-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cart_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Слепок корзины на момент отправки: [{name, sku, qty, unit, color, note}]', verbose_name='Состав корзины'),
        ),
    ]
