# Generated by Django 5.2.16 on 2026-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_cart_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Звонок'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Почта')], default='phone', max_length=20, verbose_name='Способ связи'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_value',
            field=models.CharField(blank=True, help_text='Ник/ссылка Telegram, номер WhatsApp или почта — если выбран не звонок', max_length=200, verbose_name='Контакт для связи'),
        ),
    ]
