# Generated by Django 5.2.16 on 2026-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_contact_method_lead_contact_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_method',
            field=models.CharField(choices=[('phone', 'Звонок'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('max', 'MAX'), ('email', 'Почта')], default='phone', max_length=20, verbose_name='Способ связи'),
        ),
    ]
