# Generated by Django 5.2.16 on 2026-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cart_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Слепок корзины на момент отправки: [{name, slug, qty, material, steel_grade, finish, color, size, length, height, note}]', verbose_name='Состав корзины'),
        ),
    ]
