# Generated by Django 5.2.15 on 2026-07-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок блока')),
                ('type', models.CharField(choices=[('manual', 'Ручная подборка'), ('by_category', 'Срез по категории')], default='manual', max_length=20, verbose_name='Тип блока')),
                ('link_text', models.CharField(blank=True, help_text='Например: «Весь каталог →»', max_length=100, verbose_name='Текст ссылки')),
                ('link_url', models.CharField(blank=True, max_length=300, verbose_name='URL ссылки')),
                ('limit', models.PositiveSmallIntegerField(default=4, help_text='Сколько товаров показывать в блоке', verbose_name='Кол-во карточек')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(blank=True, help_text='Обязательно при типе «Срез по категории»', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блок главной',
                'verbose_name_plural': 'Блоки главной',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_block_items', to='home.homeblock', verbose_name='Блок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_block_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в блоке',
                'verbose_name_plural': 'Товары в блоке',
                'ordering': ['position'],
                'unique_together': {('block', 'product')},
            },
        ),
    ]
