# Generated by Django 5.2.16 on 2026-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner1_enabled', models.BooleanField(default=True, verbose_name='Баннер 1: показывать')),
                ('banner1_title', models.CharField(blank=True, default='Режем металл точно под ваш чертёж', max_length=200, verbose_name='Баннер 1: заголовок')),
                ('banner1_subtitle', models.CharField(blank=True, default='Резка в размер — от листа до готовой заготовки за 1 рабочий день', max_length=300, verbose_name='Баннер 1: подзаголовок')),
                ('banner1_button_text', models.CharField(blank=True, default='Узнать больше', max_length=60, verbose_name='Баннер 1: текст кнопки')),
                ('banner1_button_url', models.CharField(blank=True, default='/produkciya/', help_text='Если пусто — кнопка откроет форму обратного звонка.', max_length=300, verbose_name='Баннер 1: ссылка кнопки')),
                ('banner2_enabled', models.BooleanField(default=True, verbose_name='Баннер 2: показывать')),
                ('banner2_title', models.CharField(blank=True, default='Оптовые закупки от 50 000 ₽', max_length=200, verbose_name='Баннер 2: заголовок')),
                ('banner2_subtitle', models.CharField(blank=True, default='Индивидуальные цены и отсрочка платежа для постоянных клиентов', max_length=300, verbose_name='Баннер 2: подзаголовок')),
                ('banner2_button_text', models.CharField(blank=True, default='Оставить заявку', max_length=60, verbose_name='Баннер 2: текст кнопки')),
                ('banner2_button_url', models.CharField(blank=True, default='', help_text='Если пусто — кнопка откроет форму обратного звонка.', max_length=300, verbose_name='Баннер 2: ссылка кнопки')),
                ('footer_copyright', models.CharField(blank=True, default='Арвенокс. Все права защищены.', help_text='Год подставляется автоматически перед этим текстом.', max_length=200, verbose_name='Футер: копирайт')),
                ('footer_legal', models.CharField(blank=True, default='ИНН 7700000000 · г. Москва', max_length=200, verbose_name='Футер: юр. строка')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
