# Generated by Django 5.2.16 on 2026-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_legal',
            field=models.TextField(blank=True, default='ИНН 7700000000 · г. Москва', help_text='Каждая строка выводится в футере с новой строки (Enter = перенос).', max_length=300, verbose_name='Футер: юр. строка'),
        ),
    ]
