# Generated by Django 5.2.15 on 2026-07-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('h1', models.CharField(blank=True, max_length=200, verbose_name='H1')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('profile_code', models.CharField(blank=True, max_length=100, verbose_name='Номенклатурный код')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/original/', verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Высота, мм')),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Длина, м')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('unit', models.CharField(choices=[('m', 'за метр'), ('piece', 'за штуку'), ('sheet', 'за лист'), ('kg', 'за кг')], default='m', max_length=10, verbose_name='Единица цены')),
                ('in_stock', models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Наличие')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.color', verbose_name='Цвет')),
                ('finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.finish', verbose_name='Обработка')),
                ('image', models.ForeignKey(blank=True, help_text='Если не задано — показывается первое фото товара', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productimage', verbose_name='Изображение варианта')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.material', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар')),
                ('steel_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.steelgrade', verbose_name='Марка стали')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товара',
                'ordering': ['price'],
            },
        ),
    ]
