# Generated by Django 5.2.16 on 2026-07-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('references', '0002_color_color_group_color_ral_code_finish_color_ui'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sku'], 'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товара'},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('m', 'метр'), ('piece', 'штука'), ('sheet', 'лист'), ('kg', 'кг')], default='m', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_group', models.CharField(blank=True, choices=[('white', 'Белые'), ('gray', 'Серые'), ('black', 'Чёрные'), ('brown', 'Коричневые'), ('blue', 'Синие'), ('green', 'Зелёные'), ('metallic', 'Металлик'), ('other', 'Другие')], help_text='Или одно фото на всю группу (синие, серые, …)', max_length=20, verbose_name='Группа цветов')),
                ('image', models.ImageField(upload_to='products/colors/', verbose_name='Изображение')),
                ('color', models.ForeignKey(blank=True, help_text='Фото под конкретный цвет', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.color', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото по цвету',
                'verbose_name_plural': 'Фото по цветам',
                'constraints': [models.UniqueConstraint(condition=models.Q(('color__isnull', False)), fields=('product', 'color'), name='uniq_product_color_image'), models.UniqueConstraint(condition=models.Q(('color_group', ''), _negated=True), fields=('product', 'color_group'), name='uniq_product_color_group_image')],
            },
        ),
    ]
