# Generated by Django 5.2.16 on 2026-07-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_custom_length',
            field=models.BooleanField(default=False, help_text='На карточке товара появится поле «Своя длина» — клиент укажет нужную длину, она уйдёт в заявку', verbose_name='Своя длина'),
        ),
    ]
