# Generated by Django 5.2.16 on 2026-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productvariant_allow_custom_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Для карточки на странице «Продукция»', upload_to='categories/', verbose_name='Изображение'),
        ),
    ]
