# Generated by Django 5.2.16 on 2026-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_image_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_custom_size',
            field=models.BooleanField(default=False, help_text='На карточке товара появится поле «Свой размер» — клиент укажет нужный размер, он уйдёт в заявку', verbose_name='Свой размер'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='Например: 6×6, 10×10, 40×20', max_length=50, verbose_name='Размер'),
        ),
    ]
