# Generated by Django 5.2.16 on 2026-07-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productvariant_allow_custom_size_productvariant_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.CharField(choices=[('material', 'Материал'), ('steel_grade', 'Марка стали'), ('finish', 'Обработка'), ('size', 'Размер'), ('length', 'Длина'), ('in_stock', 'Только в наличии')], max_length=20, verbose_name='Фильтр')),
                ('title', models.CharField(blank=True, help_text='Пусто — стандартный («Марка стали» и т.п.)', max_length=100, verbose_name='Свой заголовок')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фильтр раздела',
                'verbose_name_plural': 'Фильтры раздела',
                'ordering': ['sort_order'],
                'unique_together': {('category', 'facet')},
            },
        ),
    ]
