# Generated by Django 5.2.16 on 2026-07-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_categoryfacet'),
        ('references', '0007_materialcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('material', 'Материал'), ('steel_grade', 'Марка'), ('finish', 'Обработка')], max_length=20, verbose_name='Тип узла')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Узел опций товара',
                'verbose_name_plural': 'Дерево опций товара',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductParamValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('size', 'Размер'), ('length', 'Длина'), ('height', 'Высота')], max_length=10, verbose_name='Параметр')),
                ('value', models.CharField(help_text='Размер — «20×20», длина — «3» (м), высота — «40» (мм)', max_length=50, verbose_name='Значение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Параметр товара',
                'verbose_name_plural': 'Параметры товара',
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='productimage',
            name='uniq_product_image_finish_color',
        ),
        migrations.RemoveConstraint(
            model_name='productimage',
            name='uniq_product_image_finish_group',
        ),
        migrations.RemoveConstraint(
            model_name='productimage',
            name='uniq_product_image_finish_only',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_custom_height',
            field=models.BooleanField(default=False, help_text='Аналогично — поле «Своя высота»', verbose_name='Своя высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_custom_length',
            field=models.BooleanField(default=False, help_text='Аналогично — поле «Своя длина»', verbose_name='Своя длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_custom_size',
            field=models.BooleanField(default=False, help_text='На карточке появится поле «Свой размер» — клиент укажет нужный, он уйдёт в заявку', verbose_name='Свой размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Фото для этого материала (пусто — для любого)', null=True, on_delete=django.db.models.deletion.PROTECT, to='references.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Фото под конкретный цвет', null=True, on_delete=django.db.models.deletion.PROTECT, to='references.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='finish',
            field=models.ForeignKey(blank=True, help_text='Фото для этой обработки', null=True, on_delete=django.db.models.deletion.PROTECT, to='references.finish', verbose_name='Обработка'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False)), fields=('product', 'material', 'finish', 'color'), name='uniq_product_image_rule_color', nulls_distinct=False, violation_error_message='Фото-правило с такими условиями (цвет) уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('color_group', ''), _negated=True), fields=('product', 'material', 'finish', 'color_group'), name='uniq_product_image_rule_group', nulls_distinct=False, violation_error_message='Фото-правило с такими условиями (группа цветов) уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', True), ('color_group', ''), models.Q(('finish__isnull', True), ('material__isnull', True), _negated=True)), fields=('product', 'material', 'finish'), name='uniq_product_image_rule_plain', nulls_distinct=False, violation_error_message='Фото-правило с такими условиями уже есть.'),
        ),
        migrations.AddField(
            model_name='productoptionnode',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Имеет смысл только на узле-обработке', related_name='option_nodes', to='references.color', verbose_name='Доступные цвета'),
        ),
        migrations.AddField(
            model_name='productoptionnode',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_nodes', to='references.finish', verbose_name='Обработка'),
        ),
        migrations.AddField(
            model_name='productoptionnode',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_nodes', to='references.material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='productoptionnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.productoptionnode', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='productoptionnode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_nodes', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productoptionnode',
            name='steel_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_nodes', to='references.steelgrade', verbose_name='Марка стали'),
        ),
        migrations.AddField(
            model_name='productparamvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddConstraint(
            model_name='productoptionnode',
            constraint=models.UniqueConstraint(fields=('product', 'parent', 'node_type', 'material', 'steel_grade', 'finish'), name='uniq_product_option_node', nulls_distinct=False, violation_error_message='Такой узел у товара уже есть.'),
        ),
        migrations.AddConstraint(
            model_name='productparamvalue',
            constraint=models.UniqueConstraint(fields=('product', 'kind', 'value'), name='uniq_product_param_value', violation_error_message='Такое значение у этого параметра уже есть.'),
        ),
    ]
