# Generated by Django 5.2.16 on 2026-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_delete_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfacet',
            name='facet',
            field=models.CharField(choices=[('material', 'Материал'), ('steel_grade', 'Марка стали'), ('finish', 'Обработка'), ('color', 'Цвет'), ('size', 'Размер'), ('length', 'Длина'), ('in_stock', 'Только в наличии')], max_length=20, verbose_name='Фильтр'),
        ),
    ]
