# Generated by Django 5.2.16 on 2026-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_categoryfacet_facet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='Заполняется автоматически со страницы «Порядок популярных».', verbose_name='Порядок в популярных'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Поднимается выше в каталоге и в списке товаров. Порядок между популярными задаётся на странице «Порядок популярных».', verbose_name='Популярный'),
        ),
    ]
