# Generated by Django 5.2.16 on 2026-07-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_featured_order_product_is_featured'),
        ('references', '0010_alter_colorpalette_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptionnode',
            name='palette',
            field=models.ForeignKey(blank=True, help_text='Задана — цвета берутся из палитры живьём: правка палитры меняет все товары с ней. Пусто — берётся ручной набор ниже. Имеет смысл только на узле-обработке.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_nodes', to='references.colorpalette', verbose_name='Палитра цветов'),
        ),
        migrations.AlterField(
            model_name='productoptionnode',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Ручной набор цветов (используется, если палитра не выбрана). Имеет смысл только на узле-обработке', related_name='option_nodes', to='references.color', verbose_name='Доступные цвета'),
        ),
    ]
